ColumnsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
    - 
      AttributeName: "id"
      AttributeType: "S"
    - 
      AttributeName: "orderId"
      AttributeType: "N"
    KeySchema:
    - 
      AttributeName: "id"
      KeyType: "HASH"
    - 
      AttributeName: "orderId"
      KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
    TableName: ${self:custom.settings.COLUMNS_TABLE}